PATH: "assets/datasets_structured_layer/pyramidal-cells"
OUT_PATH: "output/T01_L5:SelectAll/features:pyramidal-cells/"
LAYER: "L5"
TYPES: ["TPC_A","TPC_B","TPC_C","UPC"]
NEURITE_TYPE: "apical_dendrite"

ADD_VEC: True
ADD_MORPH: True

FEATURE_EXTRACTOR:
#GLOBAL:
  # - ExtractNumberLeaves
  # - ExtractNumberBranchPoints
  # - ExtractMaximalApicalPathLength
  # - TotalPathLength
  # - AverageBranchOrder
  # - AverageRadius
#EDGE:
  - ExtractDistanceWeights
#NODE:
  - ExtractBranchingAngles
  # - ExtractCoordinates
  # - ExtractDiameters
  # - ExtractIsBranching
  # - ExtractIsIntermediate
  - ExtractIsLeaf
  - ExtractIsRoot
  - ExtractPathDistances
  - ExtractRadialDistances
  - ExtractVerticalDistances

CONFIG_MORPHOMETRICS: "src/configs/feature-morphometrics.yaml"
NORMALIZE: true

PH_F: "radial_distances"
VECTORIZATION:
  - persistence_image
  - wasserstein
  - bottleneck
  - sliced_wasserstein
  - landscape
FLATTEN: false
M_SW: 20
K_LS: 5
M_LS: 150
