PATH: "assets/datasets_structured_layer/kanari18_laylab"
OUT_PATH: "output/features/k18/"
LAYER: "L5"
TYPES: ["L5_TPC:A","L5_TPC:B","L5_TPC:C","L5_UPC"]
NEURITE_TYPE: "apical_dendrite"

ADD_VEC: True
ADD_MORPH: True

FEATURE_EXTRACTOR:
#GLOBAL:
  # - ExtractNumberLeaves
  # - ExtractNumberBranchPoints
  # - ExtractMaximalApicalPathLength
  # - TotalPathLength
  # - AverageBranchOrder
  # - AverageRadius
#EDGE:
  # - ExtractDistanceWeights
#NODE:
  # - ExtractBranchingAngles
  # - ExtractCoordinates
  # - ExtractDiameters
  # - ExtractIsBranching
  # - ExtractIsIntermediate
  # - ExtractIsLeaf
  # - ExtractIsRoot
  # - ExtractPathDistances
  - ExtractRadialDistances
  # - ExtractVerticalDistances

CONFIG_MORPHOMETRICS: "src/configs/feature-morphometrics.yaml"
NORMALIZE: true

PH_F: "radial_distances"
VECTORIZATION:
  - persistence_image
  - wasserstein
  - bottleneck
  - sliced_wasserstein
  - landscape
FLATTEN: false
M_SW: 20
K_LS: 5
M_LS: 150
