batch_size: 2
model_class: src.models.MultiConcat.MultiConcat
model_params:
  # General: 
  n_classes: 4
  bn: False
  dropout: 0
  embedding_dropout: 0
  embedding_dim: 128
  normalize_emb_weights: False

  # GNN:
  flow: target_to_source
  lambda_max: 3.0
  n_node_features: 1
  normalization: sym
  pool_name: avg

  # embeddings: Vectorization/Morphometrics/gnn:
  embeddings:
    - gnn
    - persistence_image
    #- wasserstein
    #- morphometrics
oversampling: False
n_epochs: 150
optimizer_class: torch.optim.Adam
optimizer_params:
  lr: 0.005
