batch_size: 2
model_class: src.models.NeutriteConcatMC.NeutriteConcatMC
model_params:
  # General: 
  n_classes: 4
  bn: False
  dropout: 0
  embedding_dropout: 0
  embedding_dim: 32
  normalize_emb_weights: True
  normalize_emb_temp: 0.1

  # GNN:
  flow: target_to_source
  lambda_max: 3.0
  n_node_features: 1
  normalization: sym
  pool_name: avg

  # embeddings: Vectorization/Morphometrics/gnn:
  embeddings:
    - gnn
    - persistence_image
    - wasserstein
    - bottleneck
    - sliced_wasserstein
    - landscape

    - morphometrics
  ntype_list: 
    - axon 
    - apical
oversampling: False
n_epochs: 50
optimizer_class: torch.optim.Adam
optimizer_params:
  lr: 0.001
